variable "config" {
  description = "The set of common variables that are generated by the common project config module"
  type = object({
    items = any
  })
}

variable "name" {
  description = "The name of the canary will be prepended with project and environment name"
  type        = string
}

variable "hostname" {
    description = "the hostname for the canary request"
    type        = string
}

variable "endpointpath" {
    description = "path - appended to the hostname for full api request"
    type        = string
}

variable "port" {
    description = "port to target request on"
    type        = string
}